config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'signout', to: "sessions#destroy"
  resources :users, except: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true, length: {minimum: 3, maxximum: 15}
    validates :email, presence: true, uniqueness: true
    has_many :articles
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :loggedin?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def loggedin?
        !!current_user
    end

    def require_before
        if !loggedin?
            redirect_to login_path
        end
    end

    def require_same_user
        if current_user != @article.user
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_before, except: %i[show index]
  before_action :require_same_user, only: %i[update edit destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 1)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash = "You have succesffuly logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
            if @user.save
              redirect_to articles_path
            else
             render :new
            end
    end

    def edit
   
    end

    def update
     
        if @user.update(user_params)
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show

    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password) 
    end

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # def gravatar_for(user)
    #     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #     gravatar_url =  "https//secure.gravatar.com/avatar/#{gravatar_id}"
    #     image_tag(gravatar_url, alt: user.username)
    # end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% obj.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <% if loggedin? && current_user == article.user %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end%>
        <td><%= link_to 'Show', article %></td>
       
        <td><%= article.user.username %></td>
        <td><%= time_ago_in_words(article.created_at)%> ago</td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>
<%= will_paginate %>
<%= render "article", obj: @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>
<% if loggedin? && current_user == @article.user %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<% end%>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if loggedin? %>
  <h2><%= link_to 'Log out', signout_path, method: :delete %></h2>
<% else %>
  <h2><%= link_to 'Log in', login_path %></h2> 
  <h2><%= link_to 'Sign up', signup_path %></h2>
<% end%>
  
 
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>
  
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>
  
    <div class="actions">
      <%= form.submit(@user.new_record? ? "Sign up" : "Edit Account") %>
    </div>
  <% end %>
  

app/views/users/edit.html.erb
<h1>Edit User</h1>


<%= render "form" %>

app/views/users/new.html.erb
<h1>This is signup </h1>


<%= render "form" %>

app/views/users/show.html.erb
<h1>User show page</h1>

<%= @user.username %>

<%= render "articles/article", obj: @user.articles %>